=== enricovianello/storm/etc/namespace-1.3.18.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by RitZ (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="aclMode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AoT"/>
				<xs:enumeration value="JiT"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="disk-quota-check" type="xs:boolean"/>
	<xs:complexType name="app-ruleType">
		<xs:sequence>
			<xs:element name="subjects" type="subjectsType"/>
			<xs:element ref="approachable-fs"/>
			<xs:element ref="space-rel-path" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
	</xs:complexType>
	<xs:element name="approachable-fs" type="xs:string"/>
	<xs:complexType name="approachable-rulesType">
		<xs:sequence>
			<xs:element name="app-rule" type="app-ruleType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="capabilitiesType">
		<xs:sequence>
			<xs:element ref="aclMode"/>
			<xs:element ref="disk-quota-check" minOccurs="0"/>
			<xs:element name="trans-prot" type="trans-protType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="defaults-valuesType">
		<xs:sequence>
			<xs:element name="space" type="spaceType"/>
			<xs:element name="file" type="fileType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="dn" type="xs:string"/>
	<xs:complexType name="fileType">
		<xs:attribute name="lifetime" type="xs:long" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="filesystemType">
		<xs:sequence>
			<xs:element name="space-token-description"/>
			<xs:element ref="root"/>
			<xs:element ref="filesystem-driver"/>
			<xs:element ref="spacesystem-driver"/>
			<xs:element ref="authorization-source" minOccurs="0"/>
			<xs:element name="properties" type="propertiesType"/>
			<xs:element name="capabilities" type="capabilitiesType"/>
			<xs:element name="defaults-values" type="defaults-valuesType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		<xs:attribute name="fs_type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="ext3"/>
					<xs:enumeration value="gpfs"/>
					<xs:enumeration value="xfs"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="filesystem-driver" nillable="false">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="it.grid.storm.filesystem.swig.posixfs"/>
				<xs:enumeration value="it.grid.storm.filesystem.swig.gpfs"/>
				<xs:enumeration value="it.grid.storm.filesystem.swig.gpfs23"/>
				<xs:enumeration value="it.grid.storm.filesystem.swig.xfs"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="filesystemsType">
		<xs:sequence>
			<xs:element name="filesystem" type="filesystemType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="host" type="xs:string"/>
	<xs:complexType name="map-ruleType">
		<xs:sequence>
			<xs:element ref="stfn-root"/>
			<xs:element ref="mapped-fs"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
	</xs:complexType>
	<xs:element name="mapped-fs" type="xs:string"/>
	<xs:complexType name="mapping-rulesType">
		<xs:sequence>
			<xs:element name="map-rule" type="map-ruleType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="namespace">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="filesystems" type="filesystemsType"/>
				<xs:element name="mapping-rules" type="mapping-rulesType"/>
				<xs:element name="approachable-rules" type="approachable-rulesType"/>
			</xs:sequence>
			<xs:attribute name="version" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="port" type="xs:string"/>
	<xs:complexType name="protType">
		<xs:sequence>
			<xs:element ref="schema"/>
			<xs:element ref="host" minOccurs="0"/>
			<xs:element ref="port" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="file"/>
					<xs:enumeration value="gsiftp"/>
					<xs:enumeration value="rfio"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="root" type="xs:string" nillable="false"/>
	<xs:element name="schema">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="file"/>
				<xs:enumeration value="gsiftp"/>
				<xs:enumeration value="rfio"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="spaceType">
		<xs:attribute name="lifetime" type="xs:long" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="guarsize" type="xs:long" use="required"/>
		<xs:attribute name="totalsize" type="xs:long" use="required"/>
	</xs:complexType>
	<xs:element name="space-rel-path" type="xs:string"/>
	<xs:element name="spacesystem-driver" nillable="false">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="it.grid.storm.filesystem.GPFSSpaceSystem"/>
				<xs:enumeration value="it.grid.storm.filesystem.MockSpaceSystem"/>
				<xs:enumeration value="it.grid.storm.filesystem.XFSSpaceSystem"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="authorization-source" nillable="false">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="permit-all"/>
				<xs:enumeration value="deny-all"/>
				<xs:enumeration value="file-catalog-ecar"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="spacetype" type="xs:string"/>
	<xs:element name="stfn-root" type="xs:string"/>
	<xs:complexType name="subjectsType">
		<xs:sequence>
			<xs:element ref="dn"/>
			<xs:element ref="vo-name" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="trans-protType">
		<xs:sequence>
			<xs:element name="prot" type="protType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="vo-name" type="xs:string"/>
	<xs:element name="RetentionPolicy">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="custodial"/>
				<xs:enumeration value="output"/>
				<xs:enumeration value="replica"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AccessLatency">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="online"/>
				<xs:enumeration value="nearline"/>
				<xs:enumeration value="offline"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ExpirationMode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="neverExpire"/>
				<xs:enumeration value="warnWhenExpire"/>
				<xs:enumeration value="releaseWhenExpire"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="UnitType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="Byte"/>
			<xs:enumeration value="KB"/>
			<xs:enumeration value="MB"/>
			<xs:enumeration value="GB"/>
			<xs:enumeration value="TB"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="TotalSizeType">
		<xs:simpleContent>
			<xs:extension base="xs:long">
				<xs:attribute name="unit" type="UnitType" use="optional" default="Byte"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="propertiesType">
		<xs:sequence>
			<xs:element ref="RetentionPolicy"/>
			<xs:element ref="AccessLatency"/>
			<xs:element ref="ExpirationMode"/>
			<xs:element name="TotalOnlineSize" type="TotalSizeType"/>
			<xs:element name="TotalNearlineSize" type="TotalSizeType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== enricovianello/storm/etc/namespace_1.3.18_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<namespace version="1.3.18" xsi:noNamespaceSchemaLocation="namespace-1.3.18.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <filesystems>
        <filesystem name="scratch-FS" fs_type="ext3">
            <space-token-description>default</space-token-description>
            <root>/mnt/gpfs/tmp</root>
            <filesystem-driver>it.grid.storm.filesystem.swig.posixfs</filesystem-driver>
            <spacesystem-driver>it.grid.storm.filesystem.GPFSSpaceSystem</spacesystem-driver>
            <authorization-source>permit-all</authorization-source>
            <properties>
                <RetentionPolicy>custodial</RetentionPolicy>
                <AccessLatency>online</AccessLatency>
                <ExpirationMode>neverExpire</ExpirationMode>
                <TotalOnlineSize unit="GB">500</TotalOnlineSize>
                <TotalNearlineSize unit="GB">0</TotalNearlineSize>
            </properties>
            <capabilities>
                <aclMode>AoT</aclMode>
                <trans-prot>
                    <prot name="file">
                        <schema>file</schema>
                    </prot>
                    <prot name="gsiftp">
                        <schema>gsiftp</schema>
                        <host>gridftp-storm.cr.cnaf.infn.it</host>
                    </prot>
                </trans-prot>
            </capabilities>
            <defaults-values>
                <space type="permanent" lifetime="2147483647" guarsize="2147483647" totalsize="2147483647"/>
                <file type="volatile" lifetime="2147483647"/>
            </defaults-values>
        </filesystem>
        <filesystem name="LHCB-FS" fs_type="gpfs">
            <space-token-description>lhcb:LHCb_RAW</space-token-description>
            <root>/storage/gpfs_storm/grid/lcg/lhcb</root>
            <filesystem-driver>it.grid.storm.filesystem.swig.gpfs</filesystem-driver>
            <spacesystem-driver>it.grid.storm.filesystem.GPFSSpaceSystem</spacesystem-driver>
            <properties>
                <RetentionPolicy>custodial</RetentionPolicy>
                <AccessLatency>online</AccessLatency>
                <ExpirationMode>neverExpire</ExpirationMode>
                <TotalOnlineSize unit="GB">500</TotalOnlineSize>
                <TotalNearlineSize unit="Byte">0</TotalNearlineSize>
            </properties>
            <capabilities>
                <aclMode>AoT</aclMode>
                <disk-quota-check>true</disk-quota-check>
                <trans-prot>
                    <prot name="file">
                        <schema>file</schema>
                    </prot>
                    <prot name="rfio">
                        <schema>rfio</schema>
                        <host>gpfs-farm-1.cr.cnaf.infn.it</host>
                        <port>5001</port>
                    </prot>
                </trans-prot>
            </capabilities>
        </filesystem>
    </filesystems>
    <mapping-rules>
        <map-rule name="LHCB-maprule">
            <stfn-root>/lhcb</stfn-root>
            <mapped-fs>LHCB-FS</mapped-fs>
        </map-rule>
        <map-rule name="Scratch-rule">
            <stfn-root>/scratch</stfn-root>
            <mapped-fs>scratch-FS</mapped-fs>
        </map-rule>
    </mapping-rules>
    <approachable-rules>
        <app-rule name="LHCB-AppRule">
            <subjects>
                <dn>*</dn>
                <vo-name>lhcb</vo-name>
            </subjects>
            <approachable-fs>LHCB-FS*, scratch-FS</approachable-fs>
        </app-rule>
        <app-rule name="scratch-AppRule">
            <subjects>
                <dn>*</dn>
            </subjects>
            <approachable-fs>scratch-FS</approachable-fs>
            <space-rel-path>/spacefiles/</space-rel-path>
        </app-rule>
        <app-rule name="SuperUsers-AppRule">
            <subjects>
                <dn>C=IT,O=INFN,CN=Riccardo Zappi</dn>
            </subjects>
            <approachable-fs>LHCB-FS, scratch-FS*</approachable-fs>
        </app-rule>
    </approachable-rules>
</namespace>
